"""empty message

Revision ID: 641ad21a32aa
Revises: 
Create Date: 2021-04-08 16:49:27.023487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641ad21a32aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
