export const ADD_POST = 'ADD_POST'
export const CREATE_POST = 'CREATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const GET_POST = 'GET_POST'
export const POST_DETAILS = 'POST_DETAILS'

export const CREATE_COMMENT = 'CREATE_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const POST_ID = 'POST_ID'
